# fonts.yml
---
- name: Install fonts
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "{{ ansible_env.HOME }}/.local/share/fonts/"
    mode: 0644
  with_fileglob:
    - fonts/*.otf
    - fonts/*.ttf
    - fonts/*.woff
  tags:
    - fonts

- name: Update font cache
  ansible.builtin.shell: fc-cache -f -v
  tags:
    - fonts
