# zsh.yml
---
- name: Install zsh
  ansible.builtin.package:
    name: zsh
    state: present
  become: yes
  tags:
    - shell
    - zsh

- name: Change shell to zsh
  ansible.builtin.shell: chsh -s $(which zsh)
  tags:
    - shell
    - zsh
  become: yes

- ansible.builtin.import_tasks: stow.yml
  vars:
    package: zsh
  tags:
    - shell
    - zsh

- name: Check if Oh-My-Zsh is already installed
  ansible.builtin.stat:
    path: "{{ ansible_env.HOME }}/.oh-my-zsh"
  register: oh_my_zsh
  tags:
    - oh-my-zsh
    - shell
    - zsh

- name: Install Oh-My-Zsh
  ansible.builtin.git:
    repo: https://github.com/ohmyzsh/ohmyzsh.git
    dest: "{{ ansible_env.HOME }}/.oh-my-zsh"
    depth: 1
  when: not oh_my_zsh.stat.exists
  tags:
    - oh-my-zsh
    - shell
    - zsh

- name: Install zsh-syntax-highlighting
  ansible.builtin.git:
    repo: "https://github.com/zsh-users/zsh-syntax-highlighting.git"
    dest: "{{ ansible_env.HOME }}/.oh-my-zsh/plugins/zsh-syntax-highlighting"
  tags:
    - oh-my-zsh
    - shell
    - zsh

- name: Enable zsh-autosuggestions
  ansible.builtin.git:
    repo: "https://github.com/zsh-users/zsh-autosuggestions"
    dest: "{{ ansible_env.HOME }}/.oh-my-zsh/plugins/zsh-autosuggestions"
  tags:
    - oh-my-zsh
    - shell
    - zsh
